### ISSUE TITLE
[1.0][운영환경] 공지 얻어올 때  Unexpected error occurred in scheduled task 예외 발생

### ISSUE THREAD

**Issue by pds0309** [pds0309/springboot-simple-fifaonline4-web#124]
**에러코드**
```linux
2021-06-16 20:30:00.045 ERROR 298407 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.NullPointerException: null
        at com.simplespringboot.ff4service.service.EtcService.lambda$indexNotice$0(EtcService.java:67) ~[classes!/:na]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_292]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_292]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_292]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_292]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_292]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_292]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_292]
        at com.simplespringboot.ff4service.service.EtcService.indexNotice(EtcService.java:67) ~[classes!/:na]
        at com.simplespringboot.ff4service.service.EtcService.initEtc(EtcService.java:40) ~[classes!/:na]
        at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.6.jar!/:5.3.6]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.6.jar!/:5.3.6]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) [spring-context-5.3.6.jar!/:5.3.6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]

```
* 테스트 목적으로 30분마다 해당 스케줄을 실행하게 해두었는데(원래 6시간) 새벽 시간에 해당 에러를 Rserve 프로세스 수만큼 반환하고 이후 Rserve 프로세스를 활용해야 되는 작업들은 실행되지 않음

**분석**
```linux
      at com.simplespringboot.ff4service.service.EtcService.indexNotice(EtcService.java:67) ~[classes!/:na]

```
* 해당부분으로 보았을 때 R로 웹 스크래핑 시 해당 url에서 해당되는 데이터를 얻을 수 없어서 REXPMismatchException 예외를 반환하고 리턴처리를 하지 않아서 Rserve 프로세스가 반환되지 않아 서버의 Rserve pool 개수만큼 모두 계속 사용중이게 되어 이후에  Rserve 프로세스를 이용한 작업 요청 시 이전에 설정해두었던 대로 계속해서 wait()  상태되고 이후의 작업들은 실행되지 않게 됨

**원인**
* 목요일은 해당 게임의 점검날인데 새벽에 점검으로 인해 그 시간에 해당 홈페이지를 접속할 수 없었거나 해당 url에서 점검시간 동안 페이지 내용 변경으로 원하는 데이터를 얻지 못했던 것으로 추정함.

**근본적인 원인**
* 본인이 예외처리를 똑바로 안함

**Comment by pds0309** [comment]
**해결**
* 이벤트 목록을 가져올 수 없을 때 이전 이벤트 목록을 그대로 보여주도록 수정
* 최근 공지 목록을 가져올 수 없을 때 최근 공지가 없다고 보여주도록 수정
