### ISSUE TITLE
[1.0] [문제] Stat DB 스케줄 업데이트 에러 문제

### ISSUE THREAD

**Issue by pds0309** [pds0309/springboot-simple-fifaonline4-web#95]
* 새벽 2시마다 랭커들의 닉네임 정보를 얻어 Stat DB를 업데이트 하도록 #65 에서 스케줄 작업을 만들어 놓음
* 유저 닉네임변경 또는 계정 삭제 등의 이유로 닉네임으로 유저 id 조회 api 에서 에러를 반환할 것을 대비해 예외처리를 해두었는데 해당부분은 잘 작동함
* 에러 로그를 보니 닉네임으로 유저 id는 조회가 되었는데 해당 id로 매치정보를 찾을 수 없는 것으로 판단됨
**에러**
```
연결된 Rserve Pool을 반환합니다
 -> 연결된 pool List에서 제거합니다.
2021-05-31 02:00:37.882 ERROR 201129 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: [{"message":"User could not found"}]
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:113) ~[spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186) ~[spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125) ~[spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819) ~[spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777) ~[spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[spring-web-5.3.6.jar!/:5.3.6]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602) ~[spring-web-5.3.6.jar!/:5.3.6]
        at com.simplespringboot.ff4service.openapi.Fifa4SearchUserMatchApi.getUserMatch(Fifa4SearchUserMatchApi.java:36) ~[classes!/:na]
        at com.simplespringboot.ff4service.service.InitService.findRankderMatch(InitService.java:257) ~[classes!/:na]
        at com.simplespringboot.ff4service.service.InitService.createStat(InitService.java:216) ~[classes!/:na]
        at com.simplespringboot.ff4service.service.InitService.updateStat(InitService.java:72) ~[classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.6.jar!/:5.3.6]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.6.jar!/:5.3.6]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) [spring-context-5.3.6.jar!/:5.3.6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]
```

**Comment by pds0309** [comment]
* R 웹 스크래핑 - OK
* 유저 닉네임으로 아이디 조회 - OK
* 아이디 식별 안 될 경우에 대한 예외 처리 - OK

**문제점**
* open api 에서 닉네임으로 유저 조회 시 아이디가 잘 나오지만 아이디로 다시 닉네임을 조회하면 User Could not Found 에러가 뜸
* 즉 아이디 자체가 잘못되었다고 할 수 있음.

**해결방안**
* 유저 Id를 통해 open api 를 조회하는 모든 로직에서 찾을 수 없을 때에 대한 예외를 처리하면 될 것 같음

**Comment by pds0309** [comment]
일정시간마다 Stat 정보가 잘 저장되는 것을 확인함

**Comment by pds0309** [comment]
현재 순위경기 시즌 선수들만 보여줄 수 있도록 Statservice 변경 및 Statrepository 쿼리 추가필요
